"""Service module to handle communication and reasoning tasks using AI models."""

import os
from google import genai
from dotenv import load_dotenv

# Load environment variables from the .env file
load_dotenv()

# Retrieve the API key from environment variables
api_key = os.getenv("GEMINI_API_KEY")

# Initialize the Gemini Client
client = None
if api_key:
    client = genai.Client(api_key=api_key)


def generate_response(prompt):
    """
    Generates a response from the Google Gemini model for a given text prompt.
    
    Parameters:
        prompt (str): The text input prompt.
        
    Returns:
        str: The text response generated by the model.
        
    Raises:
        ValueError: If the API key is missing.
        Exception: For API execution errors.
    """
    global client
    
    # If client is not initialized, check for API key again
    if not client:
        current_key = os.getenv("GEMINI_API_KEY")
        if not current_key:
            raise ValueError(
                "GEMINI_API_KEY is not set or configured. Please set it in your .env file."
            )
        client = genai.Client(api_key=current_key)
        
    try:
        # Use gemini-2.5-flash as the recommended modern and fast model
        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=prompt,
        )
        return response.text
    except Exception as e:
        # Catch and surface any execution errors
        raise Exception(f"Gemini API failure: {str(e)}")
