"""Service module to handle communication and reasoning tasks using Google Gemini models."""

import os
from google import genai
from google.genai import types
from dotenv import load_dotenv

# Load configuration values from the .env environment file
load_dotenv()

# Initialize global client container
_client_instance = None


def _get_client():
    """
    Retrieves or initializes the global Google Gemini API client instance.
    
    This function implements the Singleton pattern to ensure only a single client
    is created and shared across functions.
    
    Returns:
        genai.Client: The initialized client object.
        
    Raises:
        ValueError: If GEMINI_API_KEY is not defined in env variables or .env.
    """
    global _client_instance
    
    if _client_instance is None:
        api_key = os.getenv("GEMINI_API_KEY")
        if not api_key:
            raise ValueError(
                "GEMINI_API_KEY environment variable is missing.\n\n"
                "To fix this issue:\n"
                "1. Check if a '.env' file exists in your project root directory.\n"
                "2. Ensure it contains the line: GEMINI_API_KEY=your_actual_api_key\n"
                "3. Restart the Streamlit application server."
            )
        # Initialize client with key explicitly, ignoring default/system overrides
        _client_instance = genai.Client(api_key=api_key)
        
    return _client_instance


def generate_response(prompt):
    """
    Generates a response from the Google Gemini model for a given text prompt.
    
    Parameters:
        prompt (str): The text input prompt.
        
    Returns:
        str: The text response generated by the model.
        
    Raises:
        ValueError: If the API key configuration is missing.
        Exception: For API execution errors.
    """
    client = _get_client()
        
    try:
        # Use gemini-2.5-flash as the current standard recommended fast model
        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=prompt,
        )
        return response.text
    except Exception as e:
        raise Exception(
            f"Gemini API request failed. Please check your network connection "
            f"and verify that your API key is active. Technical details: {str(e)}"
        )


def generate_summary_sections(extracted_text):
    """
    Generates three structured summaries (Executive Summary, Key Takeaways, Important Topics)
    for a given document text in a single JSON API call.
    
    Parameters:
        extracted_text (str): The document text content.
        
    Returns:
        dict: A dictionary with keys: 'executive_summary', 'key_takeaways', 'important_topics'.
        
    Raises:
        ValueError: If the API key is missing.
        Exception: If the API call or JSON parsing fails.
    """
    client = _get_client()
        
    prompt = (
        "Analyze the following document text and generate three structured sections:\n"
        "1. Executive Summary: A concise, executive-level summary explaining the purpose, main points, and findings.\n"
        "2. Key Takeaways: A markdown bulleted list highlighting the most critical insights or actionable conclusions.\n"
        "3. Important Topics: A markdown bulleted list highlighting the key subjects, themes, or concepts covered.\n\n"
        f"Document Text:\n{extracted_text[:40000]}\n\n"
        "Return the output as a valid JSON object with the exact keys: 'executive_summary', 'key_takeaways', 'important_topics'."
    )
    
    try:
        # Request a JSON mime type response from the Gemini client
        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=prompt,
            config=types.GenerateContentConfig(
                response_mime_type="application/json"
            )
        )
        
        # Load and parse the returned JSON string
        import json
        parsed_data = json.loads(response.text)
        return parsed_data
        
    except json.JSONDecodeError as e:
        raise Exception(
            f"Failed to parse the summary JSON payload generated by the model. "
            f"Raw text response might be malformed. Details: {str(e)}"
        )
    except Exception as e:
        raise Exception(
            f"Failed to generate structured summaries via Gemini API. Details: {str(e)}"
        )


def generate_quiz(extracted_text):
    """
    Generates a 5-question multiple-choice quiz based on the document text using Gemini.
    
    Parameters:
        extracted_text (str): The document text content.
        
    Returns:
        list: A list of 5 dictionaries, each containing 'question', 'options', and 'correct_answer'.
        
    Raises:
        ValueError: If the API key is missing.
        Exception: If the API call or JSON parsing fails.
    """
    client = _get_client()
        
    prompt = (
        "Analyze the following document text and generate a comprehension quiz containing exactly 5 multiple-choice questions.\n\n"
        "Rules:\n"
        "1. Each question must have exactly 4 distinct options.\n"
        "2. The correct answer must be one of the 4 options.\n"
        "3. Focus on key themes, definitions, methodologies, or findings in the text.\n\n"
        f"Document Text:\n{extracted_text[:40000]}\n\n"
        "Return the output as a valid JSON array of objects, where each object has the exact keys: 'question', 'options', and 'correct_answer' (options should be a list of strings, and correct_answer must be one of those strings)."
    )
    
    try:
        # Request a JSON mime type response from the Gemini client
        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=prompt,
            config=types.GenerateContentConfig(
                response_mime_type="application/json"
            )
        )
        
        # Load and parse the returned JSON string
        import json
        parsed_data = json.loads(response.text)
        return parsed_data
        
    except json.JSONDecodeError as e:
        raise Exception(
            f"Failed to parse the quiz JSON payload generated by the model. "
            f"Raw text response might be malformed. Details: {str(e)}"
        )
    except Exception as e:
        raise Exception(
            f"Failed to generate quiz via Gemini API. Details: {str(e)}"
        )
